# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_rss_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='amount_to_render',
            field=models.PositiveSmallIntegerField(verbose_name='Amount of items to render'),
        ),
        migrations.AlterField(
            model_name='rssfeed',
            name='html_template',
            field=models.TextField(blank=True, help_text='If present, the default rendering template will be overriden by this', verbose_name='Custom HTML Template'),
        ),
    ]
