# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-20 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_rss_import', '0002_auto_20170216_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsssource',
            name='job',
        ),
        migrations.AddField(
            model_name='djangojob',
            name='job_id',
            field=models.CharField(db_index=True, default='', editable=False, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
