# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-22 16:14
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_rss_import', '0003_auto_20170220_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rssimport',
            options={'verbose_name': 'RSS Import', 'verbose_name_plural': 'RSS Imports'},
        ),
        migrations.AlterModelOptions(
            name='rsssource',
            options={'verbose_name': 'RSS Source', 'verbose_name_plural': 'RSS Sources'},
        ),
        migrations.AlterField(
            model_name='rssimport',
            name='content',
            field=jsonfield.fields.JSONField(db_index=True, editable=False, verbose_name='Content imported'),
        ),
    ]
