# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-04-21 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_rss_import', '0004_auto_20170222_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='html_template',
            field=models.TextField(blank=True, help_text='If present, the default rendering template will be overriden by this. IMPORTANT: Add all the the LOAD tags at the BEGINNING of the template and the SEKIZAI tags at the END of the template, otherwise the cache could break its rendering', verbose_name='Custom HTML Template'),
        ),
    ]
